---
# tasks file for hadoop_datanode
- name: Download Java Software
  get_url:
    url: https://hadoop-softwares.s3.ap-south-1.amazonaws.com/jdk-8u171-linux-x64.rpm
    dest: /root/java.rpm

- name: Download Hadoop Software
  get_url:
    url: https://hadoop-softwares.s3.ap-south-1.amazonaws.com/hadoop-1.2.1-1.x86_64.rpm
    dest: /root/hadoop.rpm
 
- name: Install Packages
  command : "rpm -i /root/{{ item }} --force"
  loop: "{{ pkgs_name }}"

- name: Configure core-site file 
  template:
    src: "core-site.xml.j2"
    dest: "/etc/hadoop/core-site.xml"

- name: Configure hdfs-site file 
  template:
    src: "hdfs-site.xml.j2"
    dest: "/etc/hadoop/hdfs-site.xml"
        
- name: Creting directory for datanode
  file:
    path: "{{ hadoop_folder }}"
    state: directory

- name: Starting datanode service
  shell: "hadoop-daemon.sh start datanode"
  
- name: Making Hadoop Daemon Service Permanent
  lineinfile:
    path: /etc/rc.d/rc.local
    line: hadoop-daemon.sh start datanode
    mode: '0755'
